[functions.createCheckoutSession]
verify_jwt = false

[functions.verifyRecaptcha]
verify_jwt = false

[functions.stripeWebhook]
verify_jwt = false

[functions.ssLookupStyle]
verify_jwt = false

[functions.ssSearchCatalog]
verify_jwt = false

[functions.ssPlaceOrder]
verify_jwt = false

[functions.acLookupStyle]
verify_jwt = false

[functions.acSearchCatalog]
verify_jwt = false

[functions.acGetInventory]
verify_jwt = false

[functions.acGetPriceList]
verify_jwt = false

[functions.acPlaceOrder]
verify_jwt = false

[functions.acGetShippingMethods]
verify_jwt = false

[functions.acGetOrder]
verify_jwt = false

[functions.qbOAuthCallback]
verify_jwt = false

[functions.qbSync]
verify_jwt = false

[functions.qbWebhook]
verify_jwt = false

[functions.sendQuoteEmail]
verify_jwt = false

[functions.sendReply]
verify_jwt = false

[functions.adminAction]
verify_jwt = false

[functions.createQuoteFromPayload]
verify_jwt = false

[functions.fedexShipping]
verify_jwt = false

[functions.hello-world]
enabled = true
verify_jwt = true
import_map = "./functions/hello-world/deno.json"
entrypoint = "./functions/hello-world/index.ts"

[functions.dailyStats]
verify_jwt = false
