client_id = "ee3080cd7352ee07184a4c232c364a20"
name = "InkTracker"
application_url = "https://inktracker.vercel.app"
embedded = false

[auth]
redirect_urls = [
  "https://skmltfbibaqcjddmeqvi.supabase.co/functions/v1/shopifyOAuthCallback"
]

[access_scopes]
scopes = "read_products,read_inventory"

[webhooks]
api_version = "2026-04"
