-- Prevent duplicate quote_ids and order_ids within a single shop.
--
-- Background:
-- Invoice ids were locked down in 20260519_invoices_no_duplicates.sql.
-- Quotes and orders had the same exposure but no DB guard:
--
--   - The public OrderWizard used Math.random()*900+100 for quote_id
--     until PR #59 (2026-05-13) replaced it with a Date.now() base36
--     scheme. With only 900 IDs/year, statistical collisions were
--     expected at any volume.
--   - Re-running the seedDemo function, manual quote_id edits, and
--     concurrent Quote.create races could all produce same-id rows.
--   - Order ids are generated by buildOrderFromQuote.generateOrderId
--     (base36 timestamp — same scheme as the modern quotes path). Low
--     collision risk in practice but no constraint = no last-line
--     guarantee.
--
-- This migration enforces uniqueness on:
--   1. (shop_owner, quote_id) WHERE quote_id IS NOT NULL AND quote_id <> ''
--   2. (shop_owner, order_id) WHERE order_id IS NOT NULL AND order_id <> ''
--
-- Both partial indexes — anonymous/incomplete rows stay legal. Per-shop
-- scope means two different shops can have the same numbered id (correct
-- for the multi-tenant namespace model).
--
-- Pre-check: fail loud with a count of any existing duplicates so they
-- can be cleaned up manually before this migration is re-applied. Will
-- NOT silently rename user-visible ids — the shop may have already
-- emailed those numbers to customers.

DO $$
DECLARE
  v_quote_dups int;
  v_order_dups int;
BEGIN
  SELECT COUNT(*) INTO v_quote_dups FROM (
    SELECT shop_owner, quote_id
    FROM public.quotes
    WHERE quote_id IS NOT NULL AND quote_id <> ''
    GROUP BY shop_owner, quote_id
    HAVING COUNT(*) > 1
  ) d;

  SELECT COUNT(*) INTO v_order_dups FROM (
    SELECT shop_owner, order_id
    FROM public.orders
    WHERE order_id IS NOT NULL AND order_id <> ''
    GROUP BY shop_owner, order_id
    HAVING COUNT(*) > 1
  ) d;

  IF v_quote_dups > 0 THEN
    RAISE EXCEPTION
      '% (shop_owner, quote_id) pair(s) duplicated — clean up before applying. Query: SELECT shop_owner, quote_id, COUNT(*) FROM quotes GROUP BY shop_owner, quote_id HAVING COUNT(*) > 1;',
      v_quote_dups;
  END IF;

  IF v_order_dups > 0 THEN
    RAISE EXCEPTION
      '% (shop_owner, order_id) pair(s) duplicated — clean up before applying. Query: SELECT shop_owner, order_id, COUNT(*) FROM orders GROUP BY shop_owner, order_id HAVING COUNT(*) > 1;',
      v_order_dups;
  END IF;
END $$;

-- Per-shop unique quote_id. Partial so legacy/null rows stay legal.
CREATE UNIQUE INDEX IF NOT EXISTS quotes_shop_quote_id_unique
  ON public.quotes (shop_owner, quote_id)
  WHERE quote_id IS NOT NULL AND quote_id <> '';

-- Per-shop unique order_id. Partial so QB-imported or wizard-in-progress
-- rows without an order_id stay legal.
CREATE UNIQUE INDEX IF NOT EXISTS orders_shop_order_id_unique
  ON public.orders (shop_owner, order_id)
  WHERE order_id IS NOT NULL AND order_id <> '';
