-- Schema reconciliation so a fresh replay (schema.sql + migrations) matches prod
-- (audit DB-01).
--
-- schema.sql (the base, frozen 2026-05-14) + 100 migrations did NOT track the
-- many columns/roles added directly to the live DB. A fresh `db reset` therefore
-- diverges from prod and a first signup FAILS (handle_new_user inserts role
-- 'shop', but schema.sql's CHECK only allows admin/broker/user). This breaks DR
-- restore, staging, and any new environment.
--
-- This migration runs LAST, so every ADD COLUMN IF NOT EXISTS below is a no-op
-- on prod and on any column an earlier migration already created — it only fills
-- the genuinely out-of-band gaps on a fresh replay. The column list was
-- GENERATED by diffing the live REST schema against schema.sql (not hand-typed),
-- so it's complete. Out-of-band columns land nullable/no-default (best effort —
-- the app populates them); migration-managed columns keep their richer defs.
--
-- A CI check that `supabase db reset` + a signup succeeds would prevent future
-- drift (recommended follow-up).

-- ── 1. role CHECK: allow all six real roles (was admin/broker/user only) ──
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_role_check
  CHECK (role IN ('admin', 'shop', 'manager', 'employee', 'broker', 'user'));

-- ── 2. out-of-band columns (generated: live REST schema − schema.sql) ──
-- profiles (20)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS broker_phone text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS broker_address text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS broker_notes text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS broker_credentials jsonb;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS city text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS state text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS zip text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS default_tax_rate numeric;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS shop_owner text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS subscription_tier text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS subscription_status text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS trial_ends_at timestamptz;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS gmail_last_scan timestamptz;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS founding_claimed_at timestamptz;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS free_freight_thresholds jsonb;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS default_ac_warehouse text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS first_name text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_name text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS mfa_email_enabled boolean;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS manager_permissions jsonb;
-- customers (8)
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS qb_customer_id text;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS ship_to_address jsonb;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS exemption_type text;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS exemption_certificate_number text;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS exemption_certificate_path text;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS exemption_expires_at date;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS exemption_states jsonb;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS bill_to_address jsonb;
-- quotes (54)
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS rush_rate numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS extras jsonb;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS line_items jsonb;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS discount numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS tax_rate numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS deposit_pct numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS deposit_paid boolean;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS sent_to text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS sent_date timestamptz;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS client_status text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS payment_status text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS sent_to_client_at timestamptz;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS client_approved_at timestamptz;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS converted_order_id text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS converted_at timestamptz;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS qb_invoice_id text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS qb_payment_link text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS qb_synced_at timestamptz;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS broker_email text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS imprints jsonb;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS job_title text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS tax_id text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS tax_exempt boolean;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS broker_client_name text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS subtotal numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS tax numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS total numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS selected_artwork jsonb;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS expires_date date;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS payment_link text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS qb_subtotal numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS qb_tax_amount numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS qb_total numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS client_total_override numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS discount_type text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS company text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS source_email_id text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS public_token text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS broker_tax_rate numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS client_subtotal numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS client_tax numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS client_total numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS setup_screens_override integer;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS is_reorder boolean;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS setup_total numeric;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS setup_skipped_fee_ids text[];
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS setup_fee_breakdown jsonb;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS qb_doc_number text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS possible_existing_customer_id uuid;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS additional_charges jsonb;
-- orders (65)
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS line_items jsonb;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS rush_rate numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS extras jsonb;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS tax_rate numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS subtotal numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS tax numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS total numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS paid boolean;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS paid_date date;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS pdf_url text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS selected_artwork jsonb;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS broker_name text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS broker_company text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS broker_client_name text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS job_title text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS ss_order_id text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS imprints jsonb;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS tax_id text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS tax_exempt boolean;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS art_approved boolean;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS art_approved_at timestamptz;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS art_approved_by text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount_type text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS actual_cost numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS actual_labor_hours numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS actual_labor_cost numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS assigned_press text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS assigned_operator text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS step_notes jsonb;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS actual_step_dates jsonb;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS is_at_risk boolean;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS risk_reason text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS checklist jsonb;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS public_token text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_address_street text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_address_city text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_address_state text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_address_zip text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_address_country text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_weight numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_length numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_width numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_height numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_service_type text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_carrier text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS tracking_number text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_label_url text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_rate numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_status text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS completed_date date;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_email text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS quote_id text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS deposit_paid boolean;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS setup_screens_override integer;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS is_reorder boolean;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS setup_total numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS setup_skipped_fee_ids text[];
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS setup_fee_breakdown jsonb;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS scheduled_date date;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS estimated_hours numeric;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS scheduled_end_date date;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS company text;
-- invoices (4)
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS qb_doc_number text;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS qb_subtotal numeric;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS qb_tax_amount numeric;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS qb_total numeric;
-- expenses (13)
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS payment_date date;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS ref_number text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS line_items jsonb;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS memo text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS attachment_url text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS total numeric;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS is_recurring boolean;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS recurring_end_date date;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS linked_order_id text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS auto_generation_type text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS qb_expense_id text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS qb_synced_at timestamptz;
-- inventory_items (6)
ALTER TABLE public.inventory_items ADD COLUMN IF NOT EXISTS ss_style_number text;
ALTER TABLE public.inventory_items ADD COLUMN IF NOT EXISTS ss_color text;
ALTER TABLE public.inventory_items ADD COLUMN IF NOT EXISTS restock_to integer;
ALTER TABLE public.inventory_items ADD COLUMN IF NOT EXISTS supplier text;
ALTER TABLE public.inventory_items ADD COLUMN IF NOT EXISTS ordered_at timestamptz;
ALTER TABLE public.inventory_items ADD COLUMN IF NOT EXISTS ordered_qty integer;
-- commissions (1)
ALTER TABLE public.commissions ADD COLUMN IF NOT EXISTS paid_date date;
-- broker_notifications (2)
ALTER TABLE public.broker_notifications ADD COLUMN IF NOT EXISTS broker_name text;
ALTER TABLE public.broker_notifications ADD COLUMN IF NOT EXISTS broker_company text;
-- broker_performance (3)
ALTER TABLE public.broker_performance ADD COLUMN IF NOT EXISTS order_id text;
ALTER TABLE public.broker_performance ADD COLUMN IF NOT EXISTS customer_name text;
ALTER TABLE public.broker_performance ADD COLUMN IF NOT EXISTS total numeric;
-- shop_performance (6)
ALTER TABLE public.shop_performance ADD COLUMN IF NOT EXISTS order_id text;
ALTER TABLE public.shop_performance ADD COLUMN IF NOT EXISTS customer_name text;
ALTER TABLE public.shop_performance ADD COLUMN IF NOT EXISTS customer_id text;
ALTER TABLE public.shop_performance ADD COLUMN IF NOT EXISTS broker_id text;
ALTER TABLE public.shop_performance ADD COLUMN IF NOT EXISTS total numeric;
ALTER TABLE public.shop_performance ADD COLUMN IF NOT EXISTS status text;
-- shops (14)
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS quote_email_subject text;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS quote_email_body text;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS wizard_styles jsonb;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS wizard_setups jsonb;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS pricing_config jsonb;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS decoration_types jsonb;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS timezone text;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS stripe_account_id text;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS stripe_account_status text;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS production_tasks jsonb;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS presses text[];
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS brand_color text;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS qb_income_account_id text;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS qb_income_account_name text;
-- messages (4)
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS from_name text;
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS read boolean;
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS attachment_url text;
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS attachment_name text;
-- broker_documents (1)
ALTER TABLE public.broker_documents ADD COLUMN IF NOT EXISTS file_type text;
-- broker_files (3)
ALTER TABLE public.broker_files ADD COLUMN IF NOT EXISTS order_id text;
ALTER TABLE public.broker_files ADD COLUMN IF NOT EXISTS customer_name text;
ALTER TABLE public.broker_files ADD COLUMN IF NOT EXISTS date date;
